### ISSUE TITLE
no delay() and continuous mode

### ISSUE THREAD

**Issue by Redferne** [maarten-pennings/ENS210#2]
Hi,
Just found this repo and saw that you were pushing updates just now :+1: 
Can I make two requests?
- Please do not use delay() in the driver, it makes it difficult to handle low power scenarios.
- Please add support for starting in continuous measurement mode.

I will tinker a little bit with the sensor on my end as well :smile:

**Comment by maarten-pennings** [comment]
Hi,

I made an update - hope it helps you.
 - Added support for continuous mode.
 - Added example for continuous mode.
 - Added example for single shot without wait.

I close this 'issue' - if I am to quick with that, please let me know.

Maarten
